# -*- coding: utf-8 -*-
"""GradientDescend2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q3EqFvw-SZCwhr-6x4k81Dyt_aQKGvs_
"""

X = [
    1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
    11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
    21, 22, 23, 24, 25, 26, 27, 28, 29, 30,
    31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
    41, 42, 43, 44, 45, 46, 47, 48, 49, 50
]

y = [
    11, 14, 17, 20, 23, 24, 29, 31, 35, 36,
    41, 42, 46, 49, 53, 54, 59, 60, 65, 66,
    70, 72, 77, 78, 83, 84, 88, 92, 95, 96,
    101, 103, 106, 110, 111, 116, 118, 122, 123, 127,
    129, 134, 136, 138, 143, 145, 149, 150, 154, 158
]

w1 = 1.0
w0 = 0.0

# Hyperparameters
learning_rate = 0.001
threshold = 0.000001
max_epochs = 100000
n = len(X)
loss_history = []

for epoch in range(max_epochs):

    # Predict
    y_pred = [w1 * x + w0 for x in X]

    # Gradient
    dw1 = sum(X[i] * (y_pred[i] - y[i]) for i in range(n))
    dw0 = sum(y_pred[i] - y[i] for i in range(n))

    # Update
    w1 -=  learning_rate * dw1 / n
    w0 -= learning_rate * dw0 / n

    # Loss (MSE)
    loss = sum((y[i] - y_pred[i]) ** 2 for i in range(n)) / ( 2 * n)
    loss_history.append(loss)

    # Điều kiện dừng
    if len(loss_history) > 2 and abs(loss_history[-2] - loss_history[-1]) < threshold:
        print(f"Stop at epoch {epoch}, loss = {loss:.6f}")
        break

    #print (dw1,dw0,loss)
    #print(f"w1 = {w1:.4f}, w0 = {w0:.4f}")


print(f"w1 = {w1:.4f}, w0 = {w0:.4f}")
print(f"Final Loss: {loss_history[-1]:.4f}")

# Test
x_test = 6
y_test = w1 * x_test + w0
print(f"Predict for x={x_test}: {y_test:.4f}")

import matplotlib.pyplot as plt

# ===== Plot regression =====
plt.figure(figsize=(8, 5))

# Data points
plt.scatter(X, y, label="Data")

# Regression line
x_line = [min(X), max(X)]
y_line = [w1 * x + w0 for x in x_line]

plt.plot(x_line, y_line, label="Regression Line")

plt.xlabel("X")
plt.ylabel("y")
plt.title("Linear Regression")
plt.legend()
plt.grid(True)

plt.show()

# ===== Plot loss =====
plt.figure(figsize=(8, 5))

plt.plot(loss_history)

plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.title("Loss over Epochs")
plt.grid(True)

plt.show()

# Added prints to show current state of divergent parameters
print(f"Final w1: {w1:.4e}")
print(f"Final w0: {w0:.4e}")
if loss_history:
    print(f"Final Loss: {loss_history[-1]:.4e}")
else:
    print("Loss history is empty.")