# -*- coding: utf-8 -*-
"""GradientDescent1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lQfdmvObvRTQG847gPDj3k-nLWprBRD8
"""

def gradient_descent(init, learning_rate, max_inter, verbal=True):
  x = init
  history = []
  for i in range(max_inter):
    x = x - learning_rate * 2 * x
    if verbal:
      print("Time:", i+1, "  x:", "{:.2f}".format(x), "  f(x):", "{:.2f}".format(x**2))
    history.append((x, x**2))
  return history

learning_rate = -0.1
gradient_descent(10, learning_rate, 10, True)

learning_rates = [0.01, 0.1, 0.2, 0.4]

results = []

for lr in learning_rates:
    results.append(gradient_descent(10, lr, 10, False))

print(f"{'Time':<6}", end="")
for lr in learning_rates:
    print(f"{f'lr={lr}':<25}", end="")
print()
print("-"*100)
# rows
for i in range(10):
    print(f"{i+1:<6}", end="")
    for j in range(len(learning_rates)):
        x, fx = results[j][i]
        print(f"{f'x={x:.2f}, f={fx:.2f}':<25}", end="")
    print()